### ISSUE TITLE
[Feedback] Sunday, July 4, 2021 - ...

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/dev-center#57]
Hello, World!

Please report here every infrastructure/build/test issue (suspected or confirmed).

Note: Issue that implies big changes or not related to infrastructure or builds/tests are welcome as a new issue!

Cheers!

**Comment by funilrys** [comment]
https://safedns2.allover.co.za/jenkins back online. From now on, all repositories will be built once per day.

**Comment by dnmTX** [comment]
@funilrys 24 Hrs. is plenty,let's see if it's working. I'll keep an eye on it(as always)

**Comment by dnmTX** [comment]
@funilrys this is what i've noticed so far that might require some attention:
Here in the [domains.list](https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers/blob/master/domains.list) all the comments are present from the orig.list. That,i guess could be skipped to reduce overhead:
![quidsup](https://user-images.githubusercontent.com/34774426/111919568-b26a5400-8a58-11eb-9fa8-5fd1dd804634.png)

Here in the [domains.list](https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server/master/domains.list) all the domains(or at least most of them) are duplicated for some reason. There is a instance with `0.0.0.0` and one without of the same domain:
![anudeepND](https://user-images.githubusercontent.com/34774426/111919637-0117ee00-8a59-11eb-827d-ae838befca09.png)

Also some of the lists are still failing to filter,maybe it's to early and they need more time.Anyway,it's never a bad ida to check it out. Thank you 👍

**Comment by funilrys** [comment]
Should be a bit better with https://github.com/Ultimate-Hosts-Blacklist/test-launcher/commit/3934815c781b4ea9254dff02462b36fa25cae852 @dnmTX. 😼

**Comment by dnmTX** [comment]
@funilrys there is a problem with the output/result on at least [one of the lists](https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com/blob/master/volatile.list).
Look at the [LAST LINE](https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com/blob/149b9e9cf41308d9e0e36881f84ebcd6f316eff0/volatile.list#L10966).
These are bunch of domains next to each other,formating went bust i'd assume.
And i hope you still working to fix the filtering and lists updating as i don't really see big improvements so far.The larger lists are still sitting ducks and it took 5 days for conciderably [small list](https://github.com/Ultimate-Hosts-Blacklist/smed79_blacklist) (8000 domains) to get filtered and updated 🤔 
I very much hope that you still around and working on the issue. Let me know how it goes 👍

**Comment by dnmTX** [comment]
@funilrys the [problem is still present](https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com/blob/d21dd92f967ae5260c68ec34d2ba90c05ccd6be5/volatile.list#L10966),it's just another line this time !!!!!!! 🤔

**Comment by dnmTX** [comment]
@funilrys also if the lists are set to start filtering every 2 days(at least that's what info.json states) [this one](https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites) is already past due. Others could be affected as well.
Please check that as well 👍

**Comment by funilrys** [comment]
@dnmTX that issue with the `volatile.list` file is fixed. It just that if an instance is running, there will be one line until the retest from the beginning will be started - again. 

I'll try to fix the clean.list thing.

**Comment by dnmTX** [comment]
@funilrys [This One](https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites) continue having problems with the scheduling. This is the fourth day since the last filtering and still doesn't start. Obviously just restarting it won't fix it.
Also mine as well see:
https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended
...it's one of the largest lists here. One thing is that it never completed filtering,also all the lists(clean.list etc.) are missing there.
Thanks 👍

**Comment by dnmTX** [comment]
> @funilrys This One continue having problems with the scheduling. This is the fourth day since the last filtering and still doesn't start. Obviously just restarting it won't fix it.

Small correction here,the list is filtering OK(yay 🎈 ) it's just the [info.json](https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites/blob/master/info.json) is stuck on `"currently_under_test": false,` all the time.

Also @funilrys just an idea about those large lists and their failed filtering:
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended
Both lists contain domain(s) with the wording `.hostmaster.` in it. Most of those resolve in the private range `127.0.0.0...` and
this could be a problem(i think).
You neeed to set it up whatever resolves in that private range to be excluded altogether. See if it helps 👍

**Comment by dnmTX** [comment]
**ping** @funilrys 
If you don't mind inspect those two due to not updating already two weeks.
Hopefully you can find the culprit this time,prevent it from happening in the feature:
https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
https://github.com/Ultimate-Hosts-Blacklist/adblock-nocoin-list

Thank you 👍
